### ISSUE TITLE
Can't Download Spark

### ISSUE THREAD

**Issue by jojotastic777** [HexxyCraft/modpack#143]
When trying to download (or possibly update?) the pack via `java -jar packwiz-installer-bootstrap.jar https://hexxycraft.github.io/modpack/pack.toml`, packwiz fails to download the `spark` mod, resulting in the following error:
```
(246/246) Failed to download spark: Failed to make HTTP request to https://ci.lucko.me/job/spark/377/artifact/spark-fabric/build/libs/spark-1.10.39-fabric.jar: Non-successful error code from HTTP request: 404
Failed to download modpack, the following errors were encountered:
spark: link.infra.packwiz.installer.request.RequestException$Response$HTTP$ErrorCode: Failed to make HTTP request to https://ci.lucko.me/job/spark/377/artifact/spark-fabric/build/libs/spark-1.10.39-fabric.jar: Non-successful error code from HTTP request: 404
	at link.infra.packwiz.installer.target.path.HttpUrlPath.source(SourceFile:26)
	at link.infra.packwiz.installer.metadata.ModFile.getSource(SourceFile:62)
	at link.infra.packwiz.installer.metadata.IndexFile$File.getSource(SourceFile:55)
	at link.infra.packwiz.installer.DownloadTask.download(SourceFile:219)
	at link.infra.packwiz.installer.UpdateManager.processIndex$lambda-14$lambda-13(SourceFile:372)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
I did a *little bit* of investigation, and what it *seems* like has happened is that, on the `https://ci.lucko.me` CI server, all the `spark` builds older than `#378` no longer exist. Maybe the mod author deleted them to clear up some space or something?

(My apologies if there's any problems with this issue I've only written like one github issue before this one, so I'm not super familiar with the etiquette for doing so.)

**Comment by object-Object** [comment]
Thanks for the report.
